<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{7bf63626-4b20-4fda-b93b-546e8359a2c5}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	aliasDatatype_TestSuite : AliasDatatype_TestSuite;
	datatype_TestSuite : Datatype_TestSuite;
	numericDatatype_TestSuite : NumericDatatype_TestSuite;
	structuredDatatype_TestSuite : StructuredDatatype_TestSuite;
	enumDatatype_TestSuite : EnumDatatype_TestSuite;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>