<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="AliasDatatypeBase" Id="{51efc251-d562-035f-0714-2cb40d22bd49}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT AliasDatatypeBase EXTENDS DatatypeBase 
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IecType" Id="{4522de90-f1b5-0fc0-0e0b-23cb79104913}">
      <Declaration><![CDATA[PROPERTY PUBLIC IecType : T_MAXSTRING]]></Declaration>
      <Get Name="Get" Id="{87e770ed-14bd-0fd2-0898-258431f34b50}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IecType := 'ALIAS';]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>