<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="UserDefinedDatatypeBase" Id="{46f1ce56-9ece-0468-3f0b-6f6310f7daa4}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'linkalways'} 
{attribute 'no_explicit_call' := 'This FB is a CLASS and must be accessed using methods or properties'}
{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK ABSTRACT UserDefinedDatatypeBase EXTENDS DatatypeBase IMPLEMENTS I_UserDefinedDatatype
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="Protected" Id="{c0485087-525e-03d0-0c3e-1ead28aca980}" />
    <Property Name="Identifier" Id="{fad1b093-141e-0c94-3cbf-d2814230ee8f}">
      <Declaration><![CDATA[PROPERTY PUBLIC ABSTRACT Identifier : T_MAXSTRING]]></Declaration>
      <Get Name="Get" Id="{0ba07a67-9506-0b52-2c39-54987f0097d7}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="OnSerializeTypeWith" Id="{e57435fa-f18e-0790-33a1-e7b24c80ba5a}" FolderPath="Protected\">
      <Declaration><![CDATA[METHOD PROTECTED OnSerializeTypeWith
VAR_INPUT
	Serializer : I_Serializer;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[SUPER^.OnSerializeTypeWith(Serializer);
Serializer.AddKeyString('identifier',Identifier);]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>