<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{7bf63626-4b20-4fda-b93b-546e8359a2c5}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	//alias
	_HRESULT_TestSuite : _HRESULT_TestSuite;
	
	// primitive
	_BOOL_TestSuite : _BOOL_TestSuite;
    //_BYTE_TestSuite : _BYTE_TestSuite;
    _WORD_TestSuite : _WORD_TestSuite;
    //_DWORD_TestSuite : _DWORD_TestSuite;
    //_LWORD_TestSuite : _LWORD_TestSuite;
    
    //_SINT_TestSuite : _SINT_TestSuite;
    _INT_TestSuite : _INT_TestSuite;
    _DINT_TestSuite : _DINT_TestSuite;
    //_LINT_TestSuite : _LINT_TestSuite;
    
    //_USINT_TestSuite : _USINT_TestSuite;
    //_UINT_TestSuite : _UINT_TestSuite;
    //_UDINT_TestSuite : _UDINT_TestSuite;
    //_ULINT_TestSuite : _ULINT_TestSuite;
    
    //_REAL_TestSuite : _REAL_TestSuite;
    //_LREAL_TestSuite : _LREAL_TestSuite;
	
	// struct
	_TIMESTRUCT_TestSuite : _TIMESTRUCT_TestSuite;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>