<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="_BOOL_TestSuit" Id="{04424176-653a-49ad-adf2-0c9b2705b8ed}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK _BOOL_TestSuit EXTENDS TcUnit.FB_TestSuite
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Placeholder();]]></ST>
    </Implementation>
    <Method Name="Placeholder" Id="{ea3d6e63-a114-47ac-8ed8-933bb714da06}">
      <Declaration><![CDATA[METHOD PUBLIC Placeholder
VAR
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[TEST('Placeholder');

AssertTrue(Condition := TRUE, Message := '');

TEST_FINISHED();]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>